########################################################################
#                                                                      #
#      Makefile template file (you may change this title)              #
#      COMPONENT:   Makefile for Message(RULES)                        #
#      DATE:        2011/01/04                                         #
#      CREATOR:     Erisen Xu                                          #
#                                                                      #
########################################################################

# Definition for build directory
OBJ_DIR  = objs
INC_DIR  = ./
SRC_DIR  = ./

# Definitions for build command
CPP = g++ -c -D_GNU_SOURCE -fPIC -g

# Definitions for build command
CPP = g++ -c -D_GNU_SOURCE -fPIC -g

TARGET = Message

LINK = g++ -Wall -fPIC -g

CXXINCS = -I"$(INC_DIR)" -I"$(INC_DIR)/../"

CXXFLAGS = $(CXXINCS)

ALL = MK_DIR $(TARGET)

all: $(ALL)

MK_DIR:
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(OBJ_DIR)/handler

